# Generated by Django 5.0.3 on 2024-03-09 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Product Name', max_length=50)),
                ('product_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='products')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
