# Generated by Django 5.0.3 on 2024-03-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_products_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
