# Generated by Django 5.0.3 on 2024-03-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_products_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
