# Generated by Django 5.0.3 on 2024-03-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_product_productitem_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={},
        ),
        migrations.AddField(
            model_name='productitem',
            name='code',
            field=models.CharField(choices=[('A01', 'A01'), ('A02', 'A02'), ('A03', 'A03'), ('A04', 'A04'), ('B05', 'B05'), ('B06', 'B06'), ('B07', 'B07'), ('B08', 'B08'), ('C09', 'C09'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12'), ('D13', 'D13'), ('D14', 'D14'), ('D15', 'D15'), ('D16', 'D16')], default=0, max_length=3),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
