# Generated by Django 5.0.3 on 2024-03-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_productitem_product_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name_plural': 'Product Items'},
        ),
    ]
