# Generated by Django 5.0.3 on 2024-03-16 18:00

import Main.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_productitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='code',
            new_name='product_code',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
