# Generated by Django 5.0.3 on 2024-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_code_productitem_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
