# Generated by Django 5.0.3 on 2024-03-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_productitem_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendoRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_model', models.IntegerField(default=0)),
                ('serial_number', models.CharField(default='', max_length=16)),
                ('bch_wallet_address', models.CharField(default='', max_length=50)),
                ('bch_vendo_name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Product Items',
            },
        ),
    ]
