# Generated by Django 5.0.3 on 2024-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_vendoregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='bch_vendo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
