# Generated by Django 5.0.3 on 2024-03-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_remove_productitem_products_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendoregistration',
            options={'verbose_name_plural': 'Vendo Registration'},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='bch_vendo',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_code',
            field=models.CharField(choices=[('A01', 'A01'), ('B02', 'B02'), ('C03', 'C03'), ('D04', 'D04')], max_length=3),
        ),
    ]
