# Generated by Django 5.0.3 on 2024-03-28 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_vendoregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='bch_vendo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.vendoregistration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_code',
            field=models.CharField(choices=[('A01', 'A01'), ('A02', 'A02'), ('A03', 'A03'), ('A04', 'A04'), ('B05', 'B05'), ('B06', 'B06'), ('B07', 'B07'), ('B08', 'B08'), ('C09', 'C09'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12'), ('D13', 'D13'), ('D14', 'D14'), ('D15', 'D15'), ('D16', 'D16')], max_length=3),
        ),
    ]
