# Generated by Django 5.0.3 on 2024-03-28 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_productitem_bch_vendo_alter_productitem_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='bch_vendo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main.vendoregistration'),
        ),
    ]
