# Generated by Django 5.0.3 on 2024-03-28 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_alter_productitem_bch_vendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='bch_vendo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.vendoregistration'),
        ),
    ]
