# Generated by Django 5.0.3 on 2024-03-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_alter_productitem_bch_vendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoregistration',
            name='product_items_available',
            field=models.IntegerField(default=0),
        ),
    ]
