# Generated by Django 5.0.3 on 2024-05-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_vendoregistration_product_items_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Alarm',
            },
        ),
        migrations.CreateModel(
            name='BchSellTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=64, null=True)),
                ('sender_address', models.CharField(max_length=64, null=True)),
                ('destination_address', models.CharField(max_length=64, null=True)),
                ('cash_amount', models.IntegerField(null=True)),
                ('cash_minus_fee_amount', models.FloatField(default=0)),
                ('bch_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'BCH Sell Transactions',
            },
        ),
        migrations.CreateModel(
            name='BchValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bch_value', models.FloatField(default=0)),
                ('tx_hash', models.CharField(max_length=64, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CashAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_address', models.CharField(max_length=54, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cash Addresses',
            },
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='bch_vendo',
        ),
        migrations.DeleteModel(
            name='VendoRegistration',
        ),
    ]
