# Generated by Django 5.0.3 on 2024-05-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alarm_bchselltransaction_bchvalue_cashaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=256, null=True)),
                ('recipient', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.productitem')),
            ],
            options={
                'verbose_name_plural': 'Product Transactions',
            },
        ),
    ]
