# Generated by Django 5.0.3 on 2024-06-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_producttransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransactions',
            name='recipient',
            field=models.CharField(max_length=54, null=True),
        ),
    ]
