# Generated by Django 5.0.3 on 2024-06-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_alter_producttransactions_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransactions',
            name='bch_value',
            field=models.FloatField(default=0),
        ),
    ]
