# Generated by Django 5.0.3 on 2024-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_producttransactions_bch_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BchValue',
        ),
        migrations.AddField(
            model_name='producttransactions',
            name='item_hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
