# Generated by Django 5.0.3 on 2024-06-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_producttransactions_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransactions',
            name='recipient',
        ),
    ]
