# Generated by Django 5.0.3 on 2024-06-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_producttransactions_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransactions',
            name='total_paid',
            field=models.FloatField(default=0, null=True),
        ),
    ]
