# Generated by Django 5.0.3 on 2024-06-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_producttransactions_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransactions',
            name='product_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
